from typing import Dict, Optional
import logging

logger = logging.getLogger(__name__)


class ClassifierFieldHandler:
    """
    Handle fields generated by LLM classifier.

    These fields don't exist in the document, so they can't have bboxes.
    Instead, compute confidence from:
      - LLM confidence (30% weight)
      - Structural evidence (70% weight)
    """

    CLASSIFIER_FIELDS = ["document_type", "category", "risk_level", "priority"]

    def __init__(self):
        self.logger = logger

    async def handle(
        self,
        surya_results: Dict,
        extracted_fields: Dict,
        classifier_confidence: Optional[Dict] = None,
    ) -> Dict:
        """
        Handle classifier-generated fields.

        Args:
            surya_results: Surya results (to analyze document structure)
            extracted_fields: Extracted fields including classifier outputs
            classifier_confidence: Optional confidence scores from LLM classifier

        Returns:
            Updated surya_results with classifier field handling
        """

        for field_name in self.CLASSIFIER_FIELDS:
            if field_name not in extracted_fields:
                continue

            field_value = extracted_fields[field_name]

            if not field_value:
                continue

            llm_conf = 0.5
            if classifier_confidence and field_name in classifier_confidence:
                llm_conf = classifier_confidence[field_name]

            struct_conf = await self._score_by_structure(
                field_name, field_value, surya_results, extracted_fields
            )

            combined_confidence = (llm_conf * 0.3) + (struct_conf * 0.7)

            surya_results[field_name] = {
                "value": field_value,
                "bbox": None,
                "confidence": min(0.96, combined_confidence),
                "handler": "classifier",
                "confidence_breakdown": {
                    "llm_confidence": llm_conf,
                    "structural_confidence": struct_conf,
                },
                "confidence_reasons": await self._get_confidence_reasons(
                    field_name, field_value, surya_results, struct_conf
                ),
            }

            self.logger.info(
                f"Classifier handler: {field_name}={field_value} "
                f"confidence: {combined_confidence:.2%}"
            )

        return surya_results

    async def _score_by_structure(
        self,
        field_name: str,
        field_value: str,
        surya_results: Dict,
        extracted_fields: Dict,
    ) -> float:
        """Score confidence based on document structure"""

        if field_name == "document_type":
            return await self._score_document_type(field_value, surya_results)

        elif field_name == "category":
            return await self._score_category(field_value, extracted_fields, surya_results)

        elif field_name == "risk_level":
            return await self._score_risk_level(field_value, extracted_fields, surya_results)

        elif field_name == "priority":
            return await self._score_priority(field_value, extracted_fields, surya_results)

        return 0.5

    async def _score_document_type(self, doc_type: str, surya_results: Dict) -> float:
        """Score document type by checking structural indicators"""

        score = 0.0

        if doc_type.lower() == "invoice":
            required_fields = ["invoice_number", "line_items", "total_due", "vendor"]
            found_count = sum(
                1 for f in required_fields
                if f in surya_results and surya_results[f]
            )

            if found_count >= 3:
                score = 0.95
            elif found_count >= 2:
                score = 0.80
            else:
                score = 0.60

        elif doc_type.lower() == "receipt":
            if "line_items" in surya_results and "total_due" in surya_results:
                score = 0.90
            elif "total_due" in surya_results:
                score = 0.75
            else:
                score = 0.60

        else:
            field_count = sum(1 for f in surya_results if surya_results[f])
            score = min(0.85, 0.5 + (field_count / 10))

        return score

    async def _score_category(
        self,
        category: str,
        extracted_fields: Dict,
        surya_results: Dict,
    ) -> float:
        """Score category by consistency with document type and vendor"""

        vendor = extracted_fields.get("vendor", "").lower()

        doc_type_confidence = surya_results.get("document_type", {}).get("confidence", 0.5)

        vendor_category_map = {
            "health": ["hospital", "clinic", "pharmacy", "medical"],
            "retail": ["store", "shop", "market", "supermarket"],
            "tech": ["software", "it", "cloud", "tech"],
        }

        score = 0.5

        for cat_name, keywords in vendor_category_map.items():
            if category.lower() == cat_name:
                if any(kw in vendor for kw in keywords):
                    score = 0.95
                else:
                    score = 0.70 + (doc_type_confidence * 0.25)
                break

        return score

    async def _score_risk_level(
        self,
        risk_level: str,
        extracted_fields: Dict,
        surya_results: Dict,
    ) -> float:
        """Score risk level by amount, vendor, document type"""

        total_due_str = extracted_fields.get("total_due", "0")
        amount = self._parse_amount(total_due_str)

        if risk_level.lower() == "high":
            if amount > 10000:
                score = 0.90
            elif amount > 5000:
                score = 0.80
            else:
                score = 0.60

        elif risk_level.lower() == "medium":
            if 1000 < amount <= 5000:
                score = 0.90
            elif amount <= 1000:
                score = 0.70
            else:
                score = 0.65

        else:  # low
            if amount < 1000:
                score = 0.90
            elif amount < 5000:
                score = 0.75
            else:
                score = 0.50

        return score

    async def _score_priority(
        self,
        priority: str,
        extracted_fields: Dict,
        surya_results: Dict,
    ) -> float:
        """Score priority by document type and amount"""

        doc_type = extracted_fields.get("document_type", "").lower()

        score = 0.7

        if priority.lower() == "high":
            if "invoice" in doc_type:
                score = 0.85

        elif priority.lower() == "low":
            if "receipt" in doc_type:
                score = 0.85

        return score

    async def _get_confidence_reasons(
        self,
        field_name: str,
        field_value: str,
        surya_results: Dict,
        struct_conf: float,
    ) -> list:
        """Generate human-readable reasons for confidence score"""

        reasons = [
            f"Classified as {field_value}",
            f"Structural evidence: {struct_conf:.0%}",
        ]

        if field_name == "document_type" and "invoice_number" in surya_results:
            reasons.append("Found invoice_number in document")

        if field_name == "category" and "vendor" in surya_results:
            reasons.append("Vendor information available")

        return reasons

    @staticmethod
    def _parse_amount(amount_str: str) -> float:
        """Parse amount string to float"""
        try:
            import re
            match = re.search(r"[\d,]+\.?\d*", str(amount_str).replace(",", ""))
            if match:
                return float(match.group())
        except (ValueError, AttributeError):
            pass
        return 0.0
