// DashboardView — user-customizable infographic dashboard.
// Replaces the old Analytics tab. Auto-populates widgets from document types,
// lets users add/remove/reorder/configure widgets, AI-propose new ones,
// and export as a clean infographic.
//
// Grid: 4-column CSS grid. Widget sizes map to column spans:
//   small=1  medium=2  large=3  full=4

import React, { useState, useEffect, useCallback } from "react";
import { LoadingState, ErrorState } from "../components/Shell.jsx";
import {
  fetchDashboardConfig, saveDashboardConfig,
  proposeDashboardWidgets,
} from "../api/documents";
import WidgetCard from "../components/dashboard/WidgetCard.jsx";
import KpiWidget from "../components/dashboard/widgets/KpiWidget.jsx";
import DonutWidget from "../components/dashboard/widgets/DonutWidget.jsx";
import BarsWidget from "../components/dashboard/widgets/BarsWidget.jsx";
import TrendWidget from "../components/dashboard/widgets/TrendWidget.jsx";
import FeedWidget from "../components/dashboard/widgets/FeedWidget.jsx";
import TableWidget from "../components/dashboard/widgets/TableWidget.jsx";
import ComparisonWidget from "../components/dashboard/widgets/ComparisonWidget.jsx";
import HeatmapWidget from "../components/dashboard/widgets/HeatmapWidget.jsx";
import AddWidgetPanel from "../components/dashboard/AddWidgetPanel.jsx";
import WidgetConfigPanel from "../components/dashboard/WidgetConfigPanel.jsx";

const WIDGET_RENDERERS = {
  kpi: KpiWidget, donut: DonutWidget, bars: BarsWidget, trend: TrendWidget,
  feed: FeedWidget, table: TableWidget, comparison: ComparisonWidget,
  heatmap: HeatmapWidget,
};

export default function DashboardView({ onOpenDocument }) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [widgets, setWidgets] = useState([]);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [customize, setCustomize] = useState(false);
  const [addOpen, setAddOpen] = useState(false);
  const [configWidget, setConfigWidget] = useState(null);
  const [proposing, setProposing] = useState(false);
  const [aiWidgets, setAiWidgets] = useState([]);

  // Fetch config
  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchDashboardConfig();
      setWidgets(data.widgets || []);
      setAutoGenerated(data.autoGenerated || false);
    } catch (err) {
      setError(err.message || "Failed to load dashboard");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  // Save config
  const save = async (newWidgets) => {
    try {
      await saveDashboardConfig({ widgets: newWidgets });
      setWidgets(newWidgets);
    } catch (err) {
      console.error("Failed to save dashboard config", err);
    }
  };

  // Customize actions
  const removeWidget = (idx) => {
    const next = widgets.filter((_, i) => i !== idx);
    save(next);
  };

  const moveWidget = (idx, dir) => {
    const next = [...widgets];
    const target = idx + dir;
    if (target < 0 || target >= next.length) return;
    [next[idx], next[target]] = [next[target], next[idx]];
    save(next);
  };

  const configureWidget = (idx, updated) => {
    const next = [...widgets];
    next[idx] = updated;
    save(next);
    setConfigWidget(null);
  };

  const addWidget = (w) => {
    const newWidget = {
      ...w,
      id: w.id || `user_${w.kind}_${Date.now()}`,
      source: "user",
      pinned: true,
    };
    save([...widgets, newWidget]);
    setAddOpen(false);
  };

  const proposeAi = async () => {
    setProposing(true);
    try {
      const data = await proposeDashboardWidgets();
      setAiWidgets(data.proposed || []);
    } catch (err) {
      console.error("AI proposal failed", err);
    } finally {
      setProposing(false);
    }
  };

  // ── Render ────────────────────────────────────────────────────────────

  if (loading) return <LoadingState label="Building your dashboard…" />;
  if (error) return <ErrorState message={error} />;

  return (
    <div style={{ maxWidth: 1040, margin: "0 auto", display: "flex", flexDirection: "column", gap: 20 }}>
      {/* Header */}
      <div className="row between" style={{ alignItems: "flex-start", gap: 12, flexWrap: "wrap" }}>
        <div>
          <h1 className="serif" style={{ fontSize: 26, lineHeight: 1.1, margin: 0 }}>Dashboard</h1>
          <p className="ink3" style={{ fontSize: 13.5, marginTop: 5 }}>
            {autoGenerated
              ? "Auto-generated from your documents. Customize it to make it yours."
              : "Your infographic dashboard — add widgets, resize, and rearrange."}
          </p>
        </div>
        <div className="row gap-3" style={{ alignItems: "center" }}>
          {customize && (
            <button onClick={() => setAddOpen(true)}
              className="border bg2 hover-bg" style={actionBtn}>
              ＋ Add widget
            </button>
          )}
          <button onClick={() => setCustomize(!customize)}
            className="border bg2 hover-bg" style={actionBtn}>
            {customize ? "✓ Done" : "⚙ Customize"}
          </button>
        </div>
      </div>

      {/* Empty state */}
      {widgets.length === 0 ? (
        <div className="bg1 border rounded-xl" style={{ padding: "40px 20px", textAlign: "center" }}>
          <div style={{ fontSize: 36, marginBottom: 10 }}>📊</div>
          <div className="serif" style={{ fontSize: 18 }}>No widgets yet</div>
          <div className="ink3" style={{ fontSize: 13, marginTop: 6, maxWidth: 400, margin: "6px auto 0" }}>
            Upload documents to auto-populate your dashboard. Or click "Customize" to add widgets manually.
          </div>
        </div>
      ) : (
        <>
          {/* Auto-generated banner */}
          {autoGenerated && !customize && (
            <div className="bg2 border rounded-lg" style={{ padding: "10px 16px", fontSize: 12.5, color: "var(--ink2)" }}>
              💡 This dashboard was auto-generated from your document types. Click <strong>Customize</strong> to add, remove, or rearrange widgets.
            </div>
          )}

          {/* Widget grid */}
          <div style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: 14,
          }}>
            {widgets.map((w, i) => {
              const Renderer = WIDGET_RENDERERS[w.kind] || KpiWidget;
              return (
                <WidgetCard
                  key={w.id || i}
                  widget={w}
                  customize={customize}
                  onRemove={() => removeWidget(i)}
                  onConfigure={() => setConfigWidget({ widget: w, idx: i })}
                  onMoveUp={() => moveWidget(i, -1)}
                  onMoveDown={() => moveWidget(i, 1)}
                >
                  <Renderer data={w._data || {}} widget={w} onOpenDocument={onOpenDocument} />
                </WidgetCard>
              );
            })}
          </div>

          {/* Footer */}
          <div className="ink3" style={{ fontSize: 10, textAlign: "center", padding: "8px 0 20px" }}>
            Computed privately from your documents · {widgets.length} widget{widgets.length !== 1 ? "s" : ""}
          </div>
        </>
      )}

      {/* Add widget panel */}
      {addOpen && (
        <AddWidgetPanel
          onClose={() => setAddOpen(false)}
          onAdd={addWidget}
          builtinWidgets={[]}  // The backend auto-generates these; user picks from pre-filtered list
          aiWidgets={aiWidgets}
          onProposeAi={proposeAi}
        />
      )}

      {/* Configure widget panel */}
      {configWidget && (
        <WidgetConfigPanel
          widget={configWidget.widget}
          onClose={() => setConfigWidget(null)}
          onSave={(updated) => configureWidget(configWidget.idx, updated)}
        />
      )}
    </div>
  );
}

const actionBtn = {
  padding: "8px 16px", borderRadius: 999, fontSize: 13, cursor: "pointer",
  color: "var(--ink)", fontWeight: 500, border: "1px solid var(--line)",
};
